### ISSUE TITLE
Please make this the way that npm shrinkwrap works

### ISSUE THREAD

**Issue by isaacs** [zaach/npm-seal#3]
There's really no reason (except laziness) that `npm shrinkwrap` doesn't verify shasums by default.

Why not send a pull req that makes it do that?

**Comment by zaach** [comment]
+1

I'll begin working on a patch, thanks!

**Comment by wilmoore** [comment]
:+1: 

BTW, is this still happening?

**Comment by isaacs** [comment]
Turns out there is a reason.  See https://github.com/isaacs/npm/issues/2649 for more details.

Long story short: non-trivial refactoring is necessary because the code in npm has got a lot of legacy crud in it.
